-- ==== 중요한 핵심 구간 ====

-- 실행 횟수 상위 5개 SQL_ID 확인
SELECT SQL_ID, EXECUTIONS
FROM V$SQL
WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
  AND SQL_TEXT NOT LIKE '%V$SQL%'
  AND SQL_TEXT NOT LIKE '%explain plan%'
ORDER BY EXECUTIONS DESC
FETCH FIRST 5 ROWS ONLY;

-- SQL_ID를 직접 지정하여 실행계획 조회
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(
    sql_id => '0xksb200fmzq9',
    format => 'TYPICAL'
));

-- ==== 모든 SQL_ID의 PLAN_HASH_VALUE 비교 ====
-- PLAN_HASH_VALUE가 같으면 실행계획이 동일
SELECT 
    p.SQL_ID,
    s.EXECUTIONS,
    p.PLAN_HASH_VALUE,
    COUNT(*) OVER (PARTITION BY p.PLAN_HASH_VALUE) AS SAME_PLAN_COUNT
FROM V$SQL_PLAN p
JOIN V$SQL s ON p.SQL_ID = s.SQL_ID
WHERE p.SQL_ID IN (
    SELECT SQL_ID
    FROM V$SQL
    WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
      AND SQL_TEXT NOT LIKE '%V$SQL%'
      AND SQL_TEXT NOT LIKE '%explain plan%'
)
AND p.ID = 0  -- 최상위 노드만
ORDER BY s.EXECUTIONS DESC;