/* [핵심] V$SQL 통계 조회를 실행하여 실제로 "REVIEW_STATISTICS" 테이블에 핞나여 몇 종류의 SQL(실행계획으로써 hardParse)이 생성되었는지 확인. */
SELECT
    SQL_ID,
    SUBSTR(SQL_TEXT, 1, 100) AS SQL_PREVIEW,
    EXECUTIONS,
    PARSE_CALLS,
    ROUND(ELAPSED_TIME / 1000000, 3) AS TOTAL_SEC,
    ROUND(ELAPSED_TIME / NULLIF(EXECUTIONS, 0) / 1000, 2) AS AVG_MS,
    BUFFER_GETS
FROM V$SQL
WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
  AND SQL_TEXT NOT LIKE '%V$SQL%'
ORDER BY LAST_ACTIVE_TIME DESC;
--FETCH FIRST 10 ROWS ONLY;

/* HardParse에 대한 개수를 세어서 조회 */
SELECT 
    COUNT(*) AS SQL_COUNT,
    SUM(PARSE_CALLS) AS TOTAL_PARSE_CALLS
FROM V$SQL
WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
  AND SQL_TEXT NOT LIKE '%V$SQL%';

-- 여기서 부터는 상세 조회로써 별도 개별 조회 가능하나 핵심 정보 아니다

/* 모든 REVIEW_STATISTICS 관련 SQL 전체 텍스트(텍스트 길이가 길어서 짤릴 수도 있음) 한번에 확인 */
SELECT 
    t.SQL_ID,
    s.EXECUTIONS,
    s.PARSE_CALLS,
    LISTAGG(t.SQL_TEXT, '') WITHIN GROUP (ORDER BY t.PIECE) AS FULL_SQL_TEXT
FROM V$SQLTEXT t
JOIN V$SQL s ON t.SQL_ID = s.SQL_ID
WHERE t.SQL_ID IN (
    SELECT SQL_ID
    FROM V$SQL
    WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
      AND SQL_TEXT NOT LIKE '%V$SQL%'
)
GROUP BY t.SQL_ID, s.EXECUTIONS, s.PARSE_CALLS
ORDER BY s.EXECUTIONS DESC;

/* 바로 위 결과에 더해서 IN절 바인드 변수 개수까지 함께 확인 */
SELECT 
    t.SQL_ID,
    s.EXECUTIONS,
    -- 물음표 개수 = IN절 바인드 변수 개수
    LENGTH(LISTAGG(t.SQL_TEXT, '') WITHIN GROUP (ORDER BY t.PIECE)) 
        - LENGTH(REPLACE(LISTAGG(t.SQL_TEXT, '') WITHIN GROUP (ORDER BY t.PIECE), '?', '')) 
        AS BIND_VAR_COUNT,
    LISTAGG(t.SQL_TEXT, '') WITHIN GROUP (ORDER BY t.PIECE) AS FULL_SQL_TEXT
FROM V$SQLTEXT t
JOIN V$SQL s ON t.SQL_ID = s.SQL_ID
WHERE t.SQL_ID IN (
    SELECT SQL_ID
    FROM V$SQL
    WHERE UPPER(SQL_TEXT) LIKE '%REVIEW_STATISTICS%'
      AND SQL_TEXT NOT LIKE '%V$SQL%'
)
GROUP BY t.SQL_ID, s.EXECUTIONS
ORDER BY BIND_VAR_COUNT DESC;