CREATE SEQUENCE BANNED_IP_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE BANNED_IP (
    BAN_ID        NUMBER        PRIMARY KEY,
    IP_ADDRESS    VARCHAR2(45)  NOT NULL,
    REASON        VARCHAR2(200),
    BANNED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    BANNED_UNTIL  TIMESTAMP     NOT NULL
);

CREATE INDEX IDX_BANNED_IP_ADDRESS ON BANNED_IP(IP_ADDRESS);
CREATE INDEX IDX_BANNED_IP_UNTIL ON BANNED_IP(BANNED_UNTIL);

commit;