-- ============================================================
-- wherehouse 본 프로젝트 테이블 DDL (미니PC Oracle 원격 서버용)
-- 생성일: 2026-02-09
-- 대상: 61.75.54.208:1521:xe (SCOTT/tiger)
-- 근거: JPA Entity 소스코드 기반
-- ============================================================
-- 주의: ANALYSIS_* 18개 테이블은 이미 생성 및 데이터 이관 완료.
--       여기서는 나머지 13개 테이블 + 시퀀스를 생성한다.
-- ============================================================

-- ======================
-- 1. ARRESTRATE (검거율)
-- ======================
CREATE TABLE ARRESTRATE (
    ADDR        VARCHAR2(50)    NOT NULL,
    RATE        NUMBER          NOT NULL,
    CONSTRAINT PK_ARRESTRATE PRIMARY KEY (ADDR)
);

-- ======================
-- 2. CCTV (원본)
-- ======================
CREATE TABLE CCTV (
    NUMBERS     NUMBER          NOT NULL,
    ADDRESS     VARCHAR2(255),
    LATITUDE    NUMBER          NOT NULL,
    LONGITUDE   NUMBER          NOT NULL,
    CAMERACOUNT NUMBER,
    CONSTRAINT PK_CCTV PRIMARY KEY (NUMBERS)
);

-- ======================
-- 3. CCTV_GEO (배치 생성 - 지오해시 인덱싱)
-- ======================
CREATE TABLE CCTV_GEO (
    NUMBERS     NUMBER          NOT NULL,
    ADDRESS     VARCHAR2(255),
    LATITUDE    NUMBER          NOT NULL,
    LONGITUDE   NUMBER          NOT NULL,
    CAMERACOUNT NUMBER,
    GEOHASH_ID  VARCHAR2(12)    NOT NULL,
    CONSTRAINT PK_CCTV_GEO PRIMARY KEY (NUMBERS)
);

-- B-Tree 인덱스 (9-Block 그리드 검색용)
CREATE INDEX IDX_CCTV_GEO_GEOHASH ON CCTV_GEO(GEOHASH_ID);

-- ======================
-- 4. POLICEOFFICE (원본)
-- ======================
CREATE TABLE POLICEOFFICE (
    ADDRESS     VARCHAR2(255)   NOT NULL,
    LATITUDE    NUMBER          NOT NULL,
    LONGITUDE   NUMBER          NOT NULL,
    CONSTRAINT PK_POLICEOFFICE PRIMARY KEY (ADDRESS)
);

-- ======================
-- 5. POLICEOFFICE_GEO (배치 생성 - 지오해시 인덱싱)
-- ======================
CREATE TABLE POLICEOFFICE_GEO (
    ADDRESS     VARCHAR2(255)   NOT NULL,
    LATITUDE    NUMBER          NOT NULL,
    LONGITUDE   NUMBER          NOT NULL,
    GEOHASH_ID  VARCHAR2(12)    NOT NULL,
    CONSTRAINT PK_POLICEOFFICE_GEO PRIMARY KEY (ADDRESS)
);

-- B-Tree 인덱스 (9-Block 그리드 검색용)
CREATE INDEX IDX_POLICEOFFICE_GEO_GEOHASH ON POLICEOFFICE_GEO(GEOHASH_ID);

-- ======================
-- 6. MAPDATA (지도 REST API)
-- ======================
CREATE TABLE MAPDATA (
    ID          NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    GUID        NUMBER          NOT NULL,
    GUNAME      VARCHAR2(255)   NOT NULL,
    LATITUDE    NUMBER          NOT NULL,
    LONGITUDE   NUMBER          NOT NULL,
    CONSTRAINT PK_MAPDATA PRIMARY KEY (ID)
);

-- ======================
-- 7. MEMBERTBL (회원관리)
-- ======================
CREATE TABLE MEMBERTBL (
    ID          VARCHAR2(255)   NOT NULL,
    PW          VARCHAR2(255),
    NICKNAME    VARCHAR2(255),
    TEL         VARCHAR2(255),
    EMAIL       VARCHAR2(255),
    JOINDATE    DATE,
    CONSTRAINT PK_MEMBERTBL PRIMARY KEY (ID)
);

-- ======================
-- 8. USERENTITY (JWT 인증)
-- ======================
CREATE TABLE USERENTITY (
    USERID      VARCHAR2(255)   NOT NULL,
    USERNAME    VARCHAR2(255)   NOT NULL,
    PASSWORD    VARCHAR2(255)   NOT NULL,
    CONSTRAINT PK_USERENTITY PRIMARY KEY (USERID)
);

-- ======================
-- 9. USERENTITY_ROLES (JWT 권한 - @ElementCollection)
-- ======================
CREATE TABLE USERENTITY_ROLES (
    USERID      VARCHAR2(255)   NOT NULL,
    ROLES       VARCHAR2(255),
    CONSTRAINT FK_USERENTITY_ROLES FOREIGN KEY (USERID) REFERENCES USERENTITY(USERID)
);

-- ======================
-- 10. WHEREBOARD (게시판)
-- ======================
-- 시퀀스
CREATE SEQUENCE WHEREBOARDER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE WHEREBOARD (
    CONNUM          NUMBER          NOT NULL,
    USERID          VARCHAR2(255),
    TITLE           VARCHAR2(255),
    BOARDCONTENT    VARCHAR2(4000),
    REGION          VARCHAR2(255),
    HIT             NUMBER,
    BDATE           DATE,
    CONSTRAINT PK_WHEREBOARD PRIMARY KEY (CONNUM)
);

-- ======================
-- 11. COMMENTTBL (댓글)
-- ======================
-- 시퀀스
CREATE SEQUENCE COMMENTTBL_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE COMMENTTBL (
    COMMENTPRIMARY  NUMBER          NOT NULL,
    BOARDID         NUMBER,
    USERID          VARCHAR2(255),
    USERNAME        VARCHAR2(255),
    REPLYCONTENT    VARCHAR2(4000),
    CONSTRAINT PK_COMMENTTBL PRIMARY KEY (COMMENTPRIMARY)
);

-- ======================
-- 12. PROPERTIES_CHARTER (전세 매물)
-- ======================
CREATE TABLE PROPERTIES_CHARTER (
    PROPERTY_ID     VARCHAR2(32)    NOT NULL,
    APT_NM          VARCHAR2(255)   NOT NULL,
    EXCLU_USE_AR    NUMBER          NOT NULL,
    FLOOR           NUMBER          NOT NULL,
    BUILD_YEAR      NUMBER,
    DEAL_DATE       VARCHAR2(10),
    DEPOSIT         NUMBER,
    LEASE_TYPE      VARCHAR2(10),
    UMD_NM          VARCHAR2(255),
    JIBUN           VARCHAR2(255)   NOT NULL,
    SGG_CD          VARCHAR2(255)   NOT NULL,
    ADDRESS         VARCHAR2(255),
    AREA_IN_PYEONG  NUMBER,
    RGST_DATE       VARCHAR2(12),
    DISTRICT_NAME   VARCHAR2(255),
    LAST_UPDATED    TIMESTAMP,
    CONSTRAINT PK_PROPERTIES_CHARTER PRIMARY KEY (PROPERTY_ID)
);

-- ======================
-- 13. PROPERTIES_MONTHLY (월세 매물)
-- ======================
CREATE TABLE PROPERTIES_MONTHLY (
    PROPERTY_ID     VARCHAR2(32)    NOT NULL,
    APT_NM          VARCHAR2(255)   NOT NULL,
    EXCLU_USE_AR    NUMBER          NOT NULL,
    FLOOR           NUMBER          NOT NULL,
    BUILD_YEAR      NUMBER,
    DEAL_DATE       VARCHAR2(10),
    DEPOSIT         NUMBER,
    MONTHLY_RENT    NUMBER,
    LEASE_TYPE      VARCHAR2(10),
    UMD_NM          VARCHAR2(255),
    JIBUN           VARCHAR2(255)   NOT NULL,
    SGG_CD          VARCHAR2(255)   NOT NULL,
    ADDRESS         VARCHAR2(255),
    AREA_IN_PYEONG  NUMBER,
    RGST_DATE       VARCHAR2(12),
    DISTRICT_NAME   VARCHAR2(255),
    LAST_UPDATED    TIMESTAMP,
    CONSTRAINT PK_PROPERTIES_MONTHLY PRIMARY KEY (PROPERTY_ID)
);

-- ======================
-- 14. REVIEWS (리뷰 원본)
-- ======================
-- 시퀀스
CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE REVIEWS (
    REVIEW_ID       NUMBER          NOT NULL,
    PROPERTY_ID     VARCHAR2(32)    NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    RATING          NUMBER          NOT NULL,
    CONTENT         CLOB            NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_REVIEWS PRIMARY KEY (REVIEW_ID),
    CONSTRAINT UK_REVIEWS_PROPERTY_USER UNIQUE (PROPERTY_ID, USER_ID)
);

-- ======================
-- 15. REVIEW_STATISTICS (리뷰 통계)
-- ======================
CREATE TABLE REVIEW_STATISTICS (
    PROPERTY_ID             VARCHAR2(32)    NOT NULL,
    REVIEW_COUNT            NUMBER          NOT NULL,
    AVG_RATING              NUMBER(3,2)     NOT NULL,
    POSITIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    NEGATIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    LAST_CALCED             TIMESTAMP,
    CONSTRAINT PK_REVIEW_STATISTICS PRIMARY KEY (PROPERTY_ID)
);

-- ======================
-- 16. REVIEW_KEYWORDS (리뷰 키워드)
-- ======================
-- 시퀀스
CREATE SEQUENCE SEQ_KEYWORD_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE REVIEW_KEYWORDS (
    KEYWORD_ID      NUMBER          NOT NULL,
    REVIEW_ID       NUMBER          NOT NULL,
    KEYWORD         VARCHAR2(50)    NOT NULL,
    SCORE           NUMBER,
    CONSTRAINT PK_REVIEW_KEYWORDS PRIMARY KEY (KEYWORD_ID)
);

-- ============================================================
-- COMMIT
-- ============================================================
COMMIT;
