/* PROPERTIES_CHARTER 컬럼 추가(6개) */

alter table properties_charter add (
    DATA_SOURCE varchar2(10) default 'BATCH' not null,
    STATUS varchar2(10) default 'ACTIVE' not null,
    REGISTERED_USER_ID VARCHAR2(100),
    REGISTERED_AT TIMESTAMP,
    MODIFIED_AT TIMESTAMP,
    USER_PROPOSED_DEPOSIT NUMBER(15)
);

ALTER TABLE PROPERTIES_MONTHLY ADD (
    DATA_SOURCE VARCHAR(10) DEFAULT 'BATCH' NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL,
    REGISTERED_USER_ID VARCHAR(50),
    REGISTERED_AT TIMESTAMP,
    MODIFIED_AT TIMESTAMP,
    USER_PROPOSED_DEPOSIT NUMBER(15),
    USER_PROPOSED_MONTHLY_RENT NUMBER(10)
);

COMMIT;

/* 인덱스 생성 - 4개 */

-- 사용자별 등록 매물 조회용 : 단일 인덱스
CREATE INDEX IDX_PROP_CHARTER_USER
    ON PROPERTIES_CHARTER (REGISTERED_USER_ID);

-- 복합인덱스 2개
CREATE INDEX IDX_PROP_CHARTER_STATUS
    ON PROPERTIES_CHARTER (STATUS, DATA_SOURCE);

CREATE INDEX IDX_PROP_MONTHLY_STATUS
    ON PROPERTIES_MONTHLY (STATUS, DATA_SOURCE);
    
/* == 작업 내역 확인 == */

-- 컬럼 추가 확인 (13개 행 반환되어야 함)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH,
       NULLABLE, DATA_DEFAULT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('PROPERTIES_CHARTER', 'PROPERTIES_MONTHLY')
   AND COLUMN_NAME IN (
        'DATA_SOURCE','STATUS','REGISTERED_USER_ID',
        'REGISTERED_AT','MODIFIED_AT',
        'USER_PROPOSED_DEPOSIT','USER_PROPOSED_MONTHLY_RENT'
   )
 ORDER BY TABLE_NAME, COLUMN_ID;

-- 인덱스 생성 확인 (4개 행 반환되어야 함)
SELECT INDEX_NAME, TABLE_NAME, INDEX_TYPE, UNIQUENESS
  FROM USER_INDEXES
 WHERE INDEX_NAME IN (
        'IDX_PROP_CHARTER_USER','IDX_PROP_MONTHLY_USER',
        'IDX_PROP_CHARTER_STATUS','IDX_PROP_MONTHLY_STATUS'
   )
 ORDER BY TABLE_NAME, INDEX_NAME;

-- 복합 인덱스 컬럼 순서 검증 (STATUS가 position 1, DATA_SOURCE가 position 2)
SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION
  FROM USER_IND_COLUMNS
 WHERE INDEX_NAME IN ('IDX_PROP_CHARTER_STATUS','IDX_PROP_MONTHLY_STATUS')
 ORDER BY INDEX_NAME, COLUMN_POSITION;

-- 기존 배치 레코드에 DEFAULT가 제대로 적용되었는지 샘플 확인
SELECT DATA_SOURCE, STATUS, COUNT(*)
  FROM PROPERTIES_CHARTER
 GROUP BY DATA_SOURCE, STATUS;
