CREATE TABLE PROPERTY_SYNC_FAILURES (
    FAILURE_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROPERTY_ID     VARCHAR2(32)  NOT NULL,
    LEASE_TYPE      VARCHAR2(10)  NOT NULL,
    OPERATION_TYPE  VARCHAR2(20)  NOT NULL,
    FAIL_STEP       VARCHAR2(50)  NOT NULL,
    FAIL_REASON     VARCHAR2(500),
    FAIL_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    RETRY_COUNT     NUMBER DEFAULT 0,
    MAX_RETRIES     NUMBER DEFAULT 5,
    RESOLVED        CHAR(1) DEFAULT 'N',
    RESOLVED_TIME   TIMESTAMP,
    RESOLVED_METHOD VARCHAR2(20)
);

COMMIT;