-- ================================================================
-- 리뷰 테이블 전세/월세 분리 DDL
-- 목적: REVIEWS, REVIEW_KEYWORDS, REVIEW_STATISTICS를
--       전세(CHARTER)/월세(MONTHLY)별로 분리하여 FK 제약조건 설정
-- ================================================================

-- ================================================================
-- 1. 시퀀스 생성
-- ================================================================
CREATE SEQUENCE SEQ_REVIEW_CHARTER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_MONTHLY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KEYWORD_CHARTER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KEYWORD_MONTHLY_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- ================================================================
-- 2. 전세 리뷰 테이블
-- ================================================================
CREATE TABLE REVIEWS_CHARTER (
    REVIEW_ID       NUMBER          NOT NULL,
    PROPERTY_ID     CHAR(32)        NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    RATING          NUMBER(1)       NOT NULL,
    CONTENT         CLOB            NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_REVIEWS_CHARTER PRIMARY KEY (REVIEW_ID),
    CONSTRAINT UK_REVIEWS_CHARTER_PROP_USER UNIQUE (PROPERTY_ID, USER_ID),
    CONSTRAINT FK_REVIEWS_CHARTER_PROPERTY FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES_CHARTER(PROPERTY_ID)
);

-- ================================================================
-- 3. 월세 리뷰 테이블
-- ================================================================
CREATE TABLE REVIEWS_MONTHLY (
    REVIEW_ID       NUMBER          NOT NULL,
    PROPERTY_ID     CHAR(32)        NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    RATING          NUMBER(1)       NOT NULL,
    CONTENT         CLOB            NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_REVIEWS_MONTHLY PRIMARY KEY (REVIEW_ID),
    CONSTRAINT UK_REVIEWS_MONTHLY_PROP_USER UNIQUE (PROPERTY_ID, USER_ID),
    CONSTRAINT FK_REVIEWS_MONTHLY_PROPERTY FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES_MONTHLY(PROPERTY_ID)
);

-- ================================================================
-- 4. 전세 리뷰 통계 테이블
-- ================================================================
CREATE TABLE REVIEW_STATISTICS_CHARTER (
    PROPERTY_ID             CHAR(32)        NOT NULL,
    REVIEW_COUNT            NUMBER          NOT NULL,
    AVG_RATING              NUMBER(3,2)     NOT NULL,
    POSITIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    NEGATIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    LAST_CALCED             TIMESTAMP,
    CONSTRAINT PK_REVIEW_STATS_CHARTER PRIMARY KEY (PROPERTY_ID),
    CONSTRAINT FK_REVIEW_STATS_CHARTER_PROP FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES_CHARTER(PROPERTY_ID)
);

-- ================================================================
-- 5. 월세 리뷰 통계 테이블
-- ================================================================
CREATE TABLE REVIEW_STATISTICS_MONTHLY (
    PROPERTY_ID             CHAR(32)        NOT NULL,
    REVIEW_COUNT            NUMBER          NOT NULL,
    AVG_RATING              NUMBER(3,2)     NOT NULL,
    POSITIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    NEGATIVE_KEYWORD_COUNT  NUMBER          NOT NULL,
    LAST_CALCED             TIMESTAMP,
    CONSTRAINT PK_REVIEW_STATS_MONTHLY PRIMARY KEY (PROPERTY_ID),
    CONSTRAINT FK_REVIEW_STATS_MONTHLY_PROP FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTIES_MONTHLY(PROPERTY_ID)
);

-- ================================================================
-- 6. 전세 리뷰 키워드 테이블
-- ================================================================
CREATE TABLE REVIEW_KEYWORDS_CHARTER (
    KEYWORD_ID      NUMBER          NOT NULL,
    REVIEW_ID       NUMBER          NOT NULL,
    KEYWORD         VARCHAR2(50)    NOT NULL,
    SCORE           NUMBER(1),
    CONSTRAINT PK_REVIEW_KW_CHARTER PRIMARY KEY (KEYWORD_ID),
    CONSTRAINT FK_REVIEW_KW_CHARTER_REVIEW FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEWS_CHARTER(REVIEW_ID)
        ON DELETE CASCADE
);

-- ================================================================
-- 7. 월세 리뷰 키워드 테이블
-- ================================================================
CREATE TABLE REVIEW_KEYWORDS_MONTHLY (
    KEYWORD_ID      NUMBER          NOT NULL,
    REVIEW_ID       NUMBER          NOT NULL,
    KEYWORD         VARCHAR2(50)    NOT NULL,
    SCORE           NUMBER(1),
    CONSTRAINT PK_REVIEW_KW_MONTHLY PRIMARY KEY (KEYWORD_ID),
    CONSTRAINT FK_REVIEW_KW_MONTHLY_REVIEW FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEWS_MONTHLY(REVIEW_ID)
        ON DELETE CASCADE
);

-- ================================================================
-- 8. 기존 데이터 마이그레이션
-- ================================================================

-- 8-1. 리뷰 마이그레이션
INSERT INTO REVIEWS_CHARTER (REVIEW_ID, PROPERTY_ID, USER_ID, RATING, CONTENT, CREATED_AT, UPDATED_AT)
SELECT r.REVIEW_ID, r.PROPERTY_ID, r.USER_ID, r.RATING, r.CONTENT, r.CREATED_AT, r.UPDATED_AT
FROM REVIEWS r
WHERE EXISTS (SELECT 1 FROM PROPERTIES_CHARTER c WHERE c.PROPERTY_ID = r.PROPERTY_ID);

INSERT INTO REVIEWS_MONTHLY (REVIEW_ID, PROPERTY_ID, USER_ID, RATING, CONTENT, CREATED_AT, UPDATED_AT)
SELECT r.REVIEW_ID, r.PROPERTY_ID, r.USER_ID, r.RATING, r.CONTENT, r.CREATED_AT, r.UPDATED_AT
FROM REVIEWS r
WHERE EXISTS (SELECT 1 FROM PROPERTIES_MONTHLY m WHERE m.PROPERTY_ID = r.PROPERTY_ID)
AND NOT EXISTS (SELECT 1 FROM REVIEWS_CHARTER rc WHERE rc.REVIEW_ID = r.REVIEW_ID);

-- 8-2. 키워드 마이그레이션
INSERT INTO REVIEW_KEYWORDS_CHARTER (KEYWORD_ID, REVIEW_ID, KEYWORD, SCORE)
SELECT rk.KEYWORD_ID, rk.REVIEW_ID, rk.KEYWORD, rk.SCORE
FROM REVIEW_KEYWORDS rk
WHERE EXISTS (SELECT 1 FROM REVIEWS_CHARTER rc WHERE rc.REVIEW_ID = rk.REVIEW_ID);

INSERT INTO REVIEW_KEYWORDS_MONTHLY (KEYWORD_ID, REVIEW_ID, KEYWORD, SCORE)
SELECT rk.KEYWORD_ID, rk.REVIEW_ID, rk.KEYWORD, rk.SCORE
FROM REVIEW_KEYWORDS rk
WHERE EXISTS (SELECT 1 FROM REVIEWS_MONTHLY rm WHERE rm.REVIEW_ID = rk.REVIEW_ID);

-- 8-3. 통계 마이그레이션
INSERT INTO REVIEW_STATISTICS_CHARTER (PROPERTY_ID, REVIEW_COUNT, AVG_RATING, POSITIVE_KEYWORD_COUNT, NEGATIVE_KEYWORD_COUNT, LAST_CALCED)
SELECT rs.PROPERTY_ID, rs.REVIEW_COUNT, rs.AVG_RATING, rs.POSITIVE_KEYWORD_COUNT, rs.NEGATIVE_KEYWORD_COUNT, rs.LAST_CALCED
FROM REVIEW_STATISTICS rs
WHERE EXISTS (SELECT 1 FROM PROPERTIES_CHARTER c WHERE c.PROPERTY_ID = rs.PROPERTY_ID);

INSERT INTO REVIEW_STATISTICS_MONTHLY (PROPERTY_ID, REVIEW_COUNT, AVG_RATING, POSITIVE_KEYWORD_COUNT, NEGATIVE_KEYWORD_COUNT, LAST_CALCED)
SELECT rs.PROPERTY_ID, rs.REVIEW_COUNT, rs.AVG_RATING, rs.POSITIVE_KEYWORD_COUNT, rs.NEGATIVE_KEYWORD_COUNT, rs.LAST_CALCED
FROM REVIEW_STATISTICS rs
WHERE EXISTS (SELECT 1 FROM PROPERTIES_MONTHLY m WHERE m.PROPERTY_ID = rs.PROPERTY_ID)
AND NOT EXISTS (SELECT 1 FROM REVIEW_STATISTICS_CHARTER rsc WHERE rsc.PROPERTY_ID = rs.PROPERTY_ID);

COMMIT;

-- ================================================================
-- 9. 시퀀스 동기화 (마이그레이션 후 반드시 실행)
-- ================================================================
-- 마이그레이션된 MAX ID에 맞춰 시퀀스 조정 필요:
--
-- DECLARE
--   v_max NUMBER;
-- BEGIN
--   SELECT NVL(MAX(REVIEW_ID), 0) INTO v_max FROM REVIEWS_CHARTER;
--   IF v_max > 0 THEN
--     EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_REVIEW_CHARTER_ID INCREMENT BY ' || v_max;
--     EXECUTE IMMEDIATE 'SELECT SEQ_REVIEW_CHARTER_ID.NEXTVAL FROM DUAL';
--     EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_REVIEW_CHARTER_ID INCREMENT BY 1';
--   END IF;
--
--   SELECT NVL(MAX(REVIEW_ID), 0) INTO v_max FROM REVIEWS_MONTHLY;
--   IF v_max > 0 THEN
--     EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_REVIEW_MONTHLY_ID INCREMENT BY ' || v_max;
--     EXECUTE IMMEDIATE 'SELECT SEQ_REVIEW_MONTHLY_ID.NEXTVAL FROM DUAL';
--     EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_REVIEW_MONTHLY_ID INCREMENT BY 1';
--   END IF;
--
--   -- KEYWORD 시퀀스도 동일하게 처리
-- END;
-- /
