spring.application.name=wherehouse

#현재 웹 Tomcat WAS 내에서 현재 어플리케이션이 요청 받을 컨텍스트 명 설정(Boot 는 자동 설정 안됨)
server.servlet.context-path=/wherehouse

# jdbcTemplate 를 위한 dbms 연결 정보 설정
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
spring.datasource.username=SCOTT
spring.datasource.password=tiger

## Mybaties 를 위한 설정.
# Mapper Location : Mybatis에서 사용할 Mapper 파일의 경로,  resources/mapper 폴더에서 Mapper.xml로 끝나는 모든 파일을 읽어들인다.
mybatis.mapper-locations=classpath:/mapper/*Mapper.xml

# Domain Aliases : DTO, VO 등의 도메인 클래스가 포함된 패키지 경로. 
mybatis.type-aliases-package=com.wherehouse.information.model

# JDBC null settings : Mybatis의 SQL 문에 null을 파라미터로 전송할 수 있게 해준다.
mybatis.configuration.jdbc-type-for-null=null

# jsp 경로 설정 (typemelef 변경 전)
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

## error 컨트롤러 경로 설정
# 에러 페이지 기본인 화이트 라벨 종료
server.error.whitelabel.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
server.error.path=/error


